BOT_TOKEN: 
  - OTY1MTEzMzAzNzg3NTExODA4.G96GOJ.P3eWGW-mUeW_LqlSDgf1mxSif3zPjc3awict_4
  - ODk1NTEyMDExxxxxxxxxxxxxxxxxxxxx
CHANNEL_ID: 
  - 1061963468967772173
  - 87751xxxxxxxxxxxxxx
MODE: simsimi
REPLY: Y
SIMSIMI_LANG: en
DELAY: 10
DEL_AFTER: 
REPOST_LAST_CHAT: 100
